import { relations } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

// ─── Enums ────────────────────────────────────────────────────────────────────

export const payoutFrequencyEnum = pgEnum("payout_frequency", ["daily", "weekly", "monthly"]);

export const staffRoleEnum = pgEnum("staff_role", [
  "driver",
  "housekeeper",
  "cook",
  "nanny",
  "gardener",
  "security",
  "other",
]);

export const transactionTypeEnum = pgEnum("transaction_type", [
  "salary_payment",
  "bonus",
  "deduction",
  "top_up",
  "withdrawal",
]);

export const transactionStatusEnum = pgEnum("transaction_status", [
  "pending",
  "completed",
  "failed",
  "reversed",
]);

// ─── Core user table ──────────────────────────────────────────────────────────
//
// Columns required by Better Auth's Drizzle adapter: name, email, emailVerified, image.
// phone and nationalIdHash are nullable — collected during KYC, not at signup.

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  email: text("email").unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  // Saudi mobile stored normalised, e.g. "+966501234567". Nullable until KYC.
  phone: text("phone").unique(),
  // SHA-256 of raw national ID — never stored in plaintext. Nullable until KYC.
  nationalIdHash: text("national_id_hash").unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ─── Better Auth — sessions ───────────────────────────────────────────────────
//
// One row per active device session. Better Auth manages expiry and rotation.
// id is a text string (UUID) generated by Better Auth.

export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    // Opaque bearer token — mobile sends in Authorization header; web uses httpOnly cookie.
    token: text("token").notNull().unique(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [index("sessions_user_id_idx").on(t.userId)],
);

// ─── Better Auth — accounts ───────────────────────────────────────────────────
//
// One row per auth method per user. providerId = "credential" stores the
// bcrypt password hash in the password column. OAuth providers store tokens here.

export const accounts = pgTable("accounts", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
  scope: text("scope"),
  // bcrypt hash — only set when providerId = "credential"
  password: text("password"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ─── Better Auth — verifications ──────────────────────────────────────────────
//
// Short-lived tokens for email verification, magic links, and password resets.

export const verifications = pgTable("verifications", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  // Hashed token value — never store the raw token
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ─── Wallet ───────────────────────────────────────────────────────────────────

export const digitalWallets = pgTable("digital_wallets", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "restrict" }),
  iban: text("iban").notNull().unique(),
  // Balance in SAR minor units (halalas). 100 halalas = SAR 1.00.
  // integer max ≈ 21.4 M SAR — sufficient for personal wallets; promote to bigint if needed.
  balanceHalalas: integer("balance_halalas").notNull().default(0),
  currency: text("currency").notNull().default("SAR"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ─── Household staff ──────────────────────────────────────────────────────────

export const householdStaff = pgTable(
  "household_staff",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    employerId: uuid("employer_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    nameEn: text("name_en").notNull(),
    role: staffRoleEnum("role").notNull(),
    payoutFrequency: payoutFrequencyEnum("payout_frequency").notNull(),
    // Base salary in halalas — excludes one-off bonuses and deductions
    baseSalaryHalalas: integer("base_salary_halalas").notNull(),
    nextPayoutDate: timestamp("next_payout_date", { withTimezone: true }).notNull(),
    // IBAN for bank transfer or Saudi mobile for wallet-to-wallet
    targetIbanOrPhone: text("target_iban_or_phone").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [index("household_staff_employer_id_idx").on(t.employerId)],
);

// ─── Transactions ─────────────────────────────────────────────────────────────

export const transactions = pgTable(
  "transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    walletId: uuid("wallet_id")
      .notNull()
      .references(() => digitalWallets.id, { onDelete: "restrict" }),
    type: transactionTypeEnum("type").notNull(),
    // Always positive in halalas; direction implied by type
    amountHalalas: integer("amount_halalas").notNull(),
    status: transactionStatusEnum("status").notNull().default("pending"),
    staffRecipientId: uuid("staff_recipient_id").references(() => householdStaff.id, {
      onDelete: "set null",
    }),
    description: text("description"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Primary feed query: wallet's transactions ordered by time
    index("transactions_wallet_occurred_idx").on(t.walletId, t.occurredAt),
    index("transactions_staff_recipient_idx").on(t.staffRecipientId),
  ],
);

// ─── Audit log ────────────────────────────────────────────────────────────────
// Immutable SAMA-compliance trace — rows are never updated or deleted.
// action and targetType are free-form text validated by Zod at insert time;
// a pgEnum would require a migration per new feature.

export const auditLogs = pgTable(
  "audit_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    actorId: uuid("actor_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    action: text("action").notNull(),
    targetType: text("target_type").notNull(),
    // text rather than uuid — covers both internal UUIDs and external provider IDs
    targetId: text("target_id").notNull(),
    beforeState: jsonb("before_state").$type<Record<string, unknown>>(),
    afterState: jsonb("after_state").$type<Record<string, unknown>>(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("audit_logs_actor_created_idx").on(t.actorId, t.createdAt)],
);

// ─── Relations ────────────────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many }) => ({
  sessions: many(sessions),
  accounts: many(accounts),
  wallets: many(digitalWallets),
  staff: many(householdStaff),
  auditLogs: many(auditLogs),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

export const accountsRelations = relations(accounts, ({ one }) => ({
  user: one(users, { fields: [accounts.userId], references: [users.id] }),
}));

export const digitalWalletsRelations = relations(digitalWallets, ({ one, many }) => ({
  owner: one(users, { fields: [digitalWallets.userId], references: [users.id] }),
  transactions: many(transactions),
}));

export const householdStaffRelations = relations(householdStaff, ({ one, many }) => ({
  employer: one(users, { fields: [householdStaff.employerId], references: [users.id] }),
  transactions: many(transactions),
}));

export const transactionsRelations = relations(transactions, ({ one }) => ({
  wallet: one(digitalWallets, {
    fields: [transactions.walletId],
    references: [digitalWallets.id],
  }),
  staffRecipient: one(householdStaff, {
    fields: [transactions.staffRecipientId],
    references: [householdStaff.id],
  }),
}));

export const auditLogsRelations = relations(auditLogs, ({ one }) => ({
  actor: one(users, { fields: [auditLogs.actorId], references: [users.id] }),
}));
